# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors: 
  mac_executor:
    macos:
      xcode: 16.0.0
    resource_class: m2pro.medium

jobs:
  build_spm:
    executor: mac_executor
    steps:
      - checkout
      - run:
          name: "Build ScribbleEditorKit Swift Library"
          command: "swift build -c release"
  build_cmake:
    executor: mac_executor
    steps:
      - checkout
      - run:
          name: "Install CMake"
          command: "brew install cmake"
      - run:
          name: Configure CMake
          command: cmake -B build -S .
      - run:
          name: Build CMake Project
          command: cmake --build build --config Release

workflows:
  build_ios:
    jobs:
      - build_cmake
      - build_spm:
          requires:
            - build_cmake
